/**
 * 78 张韦特塔罗牌关键词（三语，单行短串）
 * 本文件由 scripts/gen-card-keywords.mjs 从 public/data/card-details.json 生成，请勿手改。
 * 重新生成：node scripts/gen-card-keywords.mjs
 */

export const CARD_KEYWORDS: Record<number, { zh: string; en: string; ja: string }> = {
  0: { zh: '主动选择、冒险精神、未知之路、信任直觉、全新开始、轻盈自由', en: 'spontaneous beginning · trusting instinct · adventurous spirit · uncharted path · unconditional freedom · fearless leap', ja: '自発的な始まり・直感への信頼・冒険心・未踏の道・無条件の自由・恐れなき跳躍' },
  1: { zh: '创造、行动、智慧、意志、沟通、潜能', en: 'creation · action · wisdom · will · communication · potential', ja: '創造・行動・知恵・意志・コミュニケーション・可能性' },
  2: { zh: '直觉、潜意识、内在智慧、静默、神秘、中立', en: 'intuition · subconscious · inner wisdom · silence · mystery · neutrality', ja: '直感・潜在意識・内なる知恵・沈黙・神秘・中立' },
  3: { zh: '丰饶、滋养、母性、创造力、感性、富足', en: 'abundance · nourishment · motherhood · creativity · sensuality · prosperity', ja: '豊穣・育み・母性・創造力・感覚・豊かさ' },
  4: { zh: '权威、秩序、领导力、责任、稳定、父权', en: 'authority · order · leadership · responsibility · stability · patriarchy', ja: '権威・秩序・リーダーシップ・責任・安定・父権' },
  5: { zh: '传统、教育、信仰、权威、仪式、导师', en: 'Tradition · Education · Faith · Authority · Ritual · Mentor', ja: '伝統・教育・信仰・権威・儀式・師匠' },
  6: { zh: '爱、结合、选择、和谐、吸引力、价值观', en: 'Love · Union · Choice · Harmony · Attraction · Values', ja: '愛・結合・選択・調和・魅力・価値観' },
  7: { zh: '意志力、胜利、驾驭、行动力、自律、突破', en: 'willpower · victory · control · action · discipline · breakthrough', ja: '意志力・勝利・制御・行動力・自律・突破' },
  8: { zh: '内在力量、勇气、耐心、温柔、自我控制、以柔克刚', en: 'inner strength · courage · patience · gentleness · self-control · soft power', ja: '内なる力・勇気・忍耐・優しさ・自制心・以柔克剛' },
  9: { zh: '内省、孤独、寻道、智慧、指引、沉思', en: 'introspection · solitude · seeking truth · wisdom · guidance · contemplation', ja: '内省・孤独・真理の探求・知恵・導き・黙想' },
  10: { zh: '命运、转机、周期、变化、无常、机遇', en: 'Destiny · Turning point · Cycles · Change · Impermanence · Opportunity', ja: '運命・転機・周期・変化・無常・チャンス' },
  11: { zh: '公平、权衡、因果、责任、法律、理性', en: 'fairness · balance · karma · responsibility · law · rationality', ja: '公平・バランス・カルマ・責任・法律・理性' },
  12: { zh: '牺牲、等待、悬停、换位思考、放下、逆势而为', en: 'sacrifice · surrender · waiting · suspension · letting go · new perspective', ja: '犠牲・待つ・宙づり・視点転換・手放す・降伏' },
  13: { zh: '转变、结束、重生、淘汰、蜕变、必然', en: 'transition · ending · rebirth · elimination · metamorphosis · inevitable', ja: '変容・終わり・再生・排除・変態・不可避' },
  14: { zh: '平衡、调和、疗愈、耐心、转化、整合', en: 'Balance · Moderation · Healing · Patience · Transformation · Integration', ja: 'バランス・調和・癒し・忍耐・変容・統合' },
  15: { zh: '诱惑、束缚、欲望、阴影、沉溺、选择', en: 'temptation · bondage · desire · shadow · addiction · choice', ja: '誘惑・束縛・欲望・影・依存・選択' },
  16: { zh: '突变、崩塌、觉醒、真相、毁灭、解放', en: 'sudden change · collapse · awakening · truth · destruction · liberation', ja: '激変・崩壊・覚醒・真実・破壊・解放' },
  17: { zh: '希望、灵感、疗愈、信念、纯净、指引', en: 'Hope · Inspiration · Healing · Faith · Purity · Guidance', ja: '希望・霊感・癒し・信念・純粋・導き' },
  18: { zh: '潜意识、幻象、直觉、恐惧、迷雾、月光', en: 'Unconscious · Illusion · Intuition · Fear · Mist · Moonlight', ja: '無意識・幻想・直感・恐怖・霧・月明かり' },
  19: { zh: '成功、活力、喜悦、自我实现、光明、纯真', en: 'success · vitality · joy · self-realization · light · innocence', ja: '成功・活力・喜び・自己実現・光・純真' },
  20: { zh: '觉醒、复活、审判、使命、重生、救赎', en: 'Awakening · Resurrection · Judgment · Calling · Rebirth · Redemption', ja: '目覚め・復活・審判・使命・再生・救済' },
  21: { zh: '圆满、完成、整合、宇宙、庆祝、永恒', en: 'completion · integration · wholeness · cosmos · celebration · eternity', ja: '完成・統合・全体性・宇宙・祝福・永遠' },
  22: { zh: '新开始、灵感火花、行动力、热情、创造力、潜能', en: 'new beginning · spark of inspiration · action · passion · creativity · potential', ja: '新しい始まり・ひらめき・行動力・情熱・創造性・可能性' },
  23: { zh: '远见、规划、抉择、扩张、冒险、掌控', en: 'vision · planning · choice · expansion · adventure · control', ja: 'ビジョン・計画・選択・拡大・冒険・支配' },
  24: { zh: '远见、扩张、等待时机、探索、合作、前瞻', en: 'foresight · expansion · timing · exploration · collaboration · vision', ja: '先見性・拡張・タイミング・探求・協力・展望' },
  25: { zh: '庆祝、和谐、稳定、归属感、家园、阶段性胜利', en: 'celebration · harmony · stability · belonging · homecoming · milestone', ja: '祝賀・調和・安定・帰属感・我が家・節目' },
  26: { zh: '竞争、冲突、意见不合、挑战、争论、磨合并进', en: 'Competition · Conflict · Disagreement · Challenge · Argument · Friction and growth', ja: '競争・対立・意見の相違・挑戦・口論・摩擦と成長' },
  27: { zh: '胜利、凯旋、公众认可、自信、荣誉、成功', en: 'victory · triumph · public recognition · confidence · honor · success', ja: '勝利・凱旋・公の認知・自信・名誉・成功' },
  28: { zh: '坚守阵地、勇敢对峙、竞争者、防御压力、孤立感、捍卫立场', en: 'Stand your ground · Brave confrontation · Competitor · Defensive pressure · Feeling isolated · Champion of principle', ja: '陣地を守る・勇敢な対決・競争者・防御的压力・孤立感・原則を擁護する' },
  29: { zh: '速度、行动、沟通、旅行、消息、延迟', en: 'speed · action · communication · travel · news · delay', ja: 'スピード・行動・コミュニケーション・旅行・知らせ・遅延' },
  30: { zh: '坚韧、防御、警惕、疲惫、毅力、坚守', en: 'resilience · defense · vigilance · fatigue · persistence · holding on', ja: '強靭さ・防御・警戒・疲労・忍耐・維持' },
  31: { zh: '过度负荷、责任压力、疲惫极限、坚持到底、学会放手、黎明前夜', en: 'burden · responsibility · completion · pressure · perseverance · overcommitment', ja: '責任・重荷・疲労・達成・忍耐・燃え尽き' },
  32: { zh: '热情、灵感、探索、创新、行动力、新开始', en: 'passion · inspiration · exploration · innovation · action · new beginnings', ja: '情熱・インスピレーション・探求・革新・行動力・新たな始まり' },
  33: { zh: '行动、冒险、热情、冲动、启动、速度', en: 'Action · Adventure · Passion · Impulse · Initiation · Speed', ja: '行動・冒険・情熱・衝動・着火・スピード' },
  34: { zh: '自信、热情、魅力、独立、创造力、领导力', en: 'confidence · passion · charm · independence · creativity · leadership', ja: '自信・情熱・魅力・独立・創造性・リーダーシップ' },
  35: { zh: '领导力、行动力、自信、成熟、创业精神、远见卓识', en: 'Leadership · Action · Confidence · Maturity · Entrepreneurship · Vision', ja: 'リーダーシップ・行動力・自信・成熟・起業精神・卓越した先見性' },
  36: { zh: '情感开启、爱的礼物、心灵的丰盈、直觉涌现、灵感启发、新的关系', en: 'Emotional Opening · Gift of Love · Heart Abundance · Intuitive Flow · Inspiration · New Relationship', ja: '感情の開花・愛の贈り物・心の豊かさ・直感の流れ・インスピレーション・新しい関係' },
  37: { zh: '爱情、结合、伙伴关系、和谐、相互吸引、和解', en: 'Love · Union · Partnership · Harmony · Mutual attraction · Reconciliation', ja: '愛・結合・パートナーシップ・調和・相互惹きつけ・和解' },
  38: { zh: '友谊、庆祝、合作、分享、欢聚、社群', en: 'friendship · celebration · community · joy · gathering · sisterhood', ja: '友情・祝福・共同体・喜び・祝祭・感謝' },
  39: { zh: '停滞、冷漠、反思、拒绝、倦怠、机遇', en: 'apathy · stagnation · introspection · refusal · boredom · missed opportunity', ja: '無関心・停滞・内省・拒絶・倦怠・機会の見逃し' },
  40: { zh: '悲伤、失落、遗憾、放手、转变、希望', en: 'grief · loss · regret · release · transition · hope', ja: '悲しみ・喪失・後悔・手放す・転機・希望' },
  41: { zh: '童年回忆、纯真善意、旧识重逢、情感馈赠、内在孩童、过去的疗愈', en: 'childhood memory · innocent kindness · reunion with old friends · emotional gift · inner child · healing the past', ja: '幼少期の想い出・無垢な優しさ・旧友との再会・感情の贈り物・インナーチャイルド・過去の癒し' },
  42: { zh: '幻想、选择、白日梦、欲望、迷惑、想象', en: 'Fantasy · Choices · Daydream · Desire · Illusion · Imagination', ja: '幻想・選択・白昼夢・欲望・錯覚・想像力' },
  43: { zh: '更深的追寻、主动离开、情感空虚、放下过往、灵性旅程、转身前行', en: 'deeper seek · voluntary leaving · emotional vacancy · letting go · spiritual journey · walking away', ja: 'より深い探求・自発的な離別・感情的空虚感・手放すこと・霊的な旅・振り返ず前進' },
  44: { zh: '愿望实现、满足感、物质丰盛、自我嘉许、社交欢愉、内心圆满', en: 'wish fulfillment · satisfaction · material abundance · self-gratification · social pleasure · inner completion', ja: '願望成就・満足感・物質的豊かさ・自己満足・社交的な喜び・内なる完了' },
  45: { zh: '正位：幸福、家庭、和谐、满足、爱、分享、逆位：疏离、家庭冲突、幻灭、失落、虚伪、孤独', en: 'happiness · family · harmony · fulfillment · love · sharing', ja: '幸福・家族・調和・満足・愛・共有' },
  46: { zh: '情感萌芽、直觉、纯真、心之所向、创意灵感、倾听内心', en: 'emotional budding · intuition · innocence · heartfelt · creative inspiration · inner listening', ja: '感情の芽生え・直感・純真・心のまま・創造的インスピレーション・内なる聴取' },
  47: { zh: '浪漫、情感表达、理想主义、灵感、温柔、直觉', en: 'romance · creativity · intuition · emotional message · dreamer · invitation', ja: '愛・ロマンス・提案・直感・芸術性・善意' },
  48: { zh: '情感智慧、同理心、直觉、疗愈、滋养、情绪边界', en: 'empathy · intuition · compassion · emotional depth · nurturing · psychic receptivity', ja: '共感・直感・成熟・優しさ・想像力・癒し' },
  49: { zh: '情感成熟、慈悲、直觉、包容、灵性领袖、情感平衡', en: 'Emotional Maturity · Compassion · Intuition · Empathy · Spiritual Guidance · Balance', ja: '感情の成熟・慈悲・直感・共感・霊的導き・バランス' },
  50: { zh: '清晰、思维、决断、真理、新起点、沟通', en: 'clarity · mind · decision · truth · new beginning · communication', ja: '明晰・思考・決断・真実・新たな始まり・コミュニケーション' },
  51: { zh: '僵局、逃避、平衡、选择困难、冷静观察、防御', en: 'stalemate · avoidance · balance · hard choice · cold observation · defense', ja: '膠着・逃避・均衡・選択困難・冷静な観察・防衛' },
  52: { zh: '心碎、悲伤、分离、放下执念、真相刺痛、疗愈', en: 'heartbreak · grief · separation · letting go · painful truth · healing', ja: '失恋・悲しみ・別れ・手放す・痛みの真実・癒し' },
  53: { zh: '休息、暂停、冥想、疗愈、蛰伏、静观', en: 'Rest · Pause · Meditation · Healing · Hibernation · Contemplation', ja: '休息・一時停止・瞑想・癒し・休眠・熟考' },
  54: { zh: '冲突、争执、得不偿失、傲慢、背叛、和解', en: 'conflict · victory · cruelty · dishonor · rivalry · defeat', ja: '勝利・代償・対立・犠牲・勝ち負け・孤立' },
  55: { zh: '过渡、疗愈、告别过去、平静、压力、旅行', en: 'transition · recovery · healing · journey · moving on · grief', ja: '移行・変容・旅立ち・過去の克服・静かな前進・回復' },
  56: { zh: '智谋、欺诈、隐藏、策略、得手、风险', en: 'deception · strategy · stealth · secrecy · self-preservation · cunning', ja: '策略・自己保身・裏切り・計画性・回避・情報操作' },
  57: { zh: '自我囚禁、限制、无力感、恐惧思维、蒙蔽、觉醒机会', en: 'self-imprisonment · restriction · helplessness · fear-driven thoughts · blindness · opportunity to awaken', ja: '自己監禁・制限・無力感・恐怖の思考・盲目・覚醒の機会' },
  58: { zh: '失眠、噩梦、焦虑、内疚、精神折磨、自我惩罚', en: 'insomnia · nightmares · anxiety · guilt · mental anguish · self-punishment', ja: '不眠・悪夢・不安・罪悪感・精神的苦痛・自己罰' },
  59: { zh: '彻底的终结、绝望谷底、背叛与打击、放下执念、重生前夜、痛定思痛', en: 'complete ending · rock bottom · betrayal · letting go · pre-dawn rebirth · painful clarity', ja: '完全な終わり・どん底・裏切り・執着の手放し・再生の前夜・痛みの果ての覚醒' },
  60: { zh: '警觉、好奇、信息收集、沟通、观察、思考', en: 'vigilance · curiosity · information gathering · communication · observation · thinking', ja: '警戒心・好奇心・情報収集・コミュニケーション・観察・思考' },
  61: { zh: '迅速决策、头脑风暴、直言不讳、行动果决、冲动鲁莽、沟通冲突', en: 'swift action · intellectual clarity · decisiveness · communication · impulsiveness · conflict', ja: '快速な決断・理論的な洞察・精神的突進・深謀遠慮・情報収集・行動力' },
  62: { zh: '独立、理性、洞察、边界、清晰、冷静', en: 'clear thinking · truth · independence · just judgment · communication · boundaries', ja: '知性・冷静さ・判断力・独立・客観性・真相' },
  63: { zh: '理性、权威、公正、判断、孤独、逻辑', en: 'intellect · justice · clarity · authority · truth · strategy', ja: '正義・理性・判断力・真実・法律・公平さ' },
  64: { zh: '务实机会、新开始、物质丰收、稳定基础、天赋礼物、行动点', en: 'practical opportunity · new beginning · material abundance · stable foundation · gift of talent · action point', ja: '現実的チャンス・新たな始まり・物質的な豊かさ・安定した基盤・才能の贈り物・行動のポイント' },
  65: { zh: '平衡、杂耍、灵活应对、多重事务、财务周转、动态稳定', en: 'Balance · Juggling · Adaptability · Multiple responsibilities · Cash flow · Dynamic stability', ja: 'バランス・ジャグリング・柔軟な対応・複数の任務・資金繰り・動的安定' },
  66: { zh: '团队合作、专业技能、建设性计划、被认可、学徒期、协同创造', en: 'teamwork · craftsmanship · building plan · recognition · apprenticeship · synergy', ja: 'チームワーク・職人技・建設的計画・認められる・見習い期間・共創' },
  67: { zh: '固守、安全、控制、吝啬、保守、恐惧失去', en: 'holding on · security · control · miserliness · conservatism · fear of loss', ja: '固執・安全・コントロール・けち・保守・喪失への恐れ' },
  68: { zh: '物质困境、孤独无助、健康危机、寻求援助、寒冬考验、希望潜伏', en: 'material hardship · loneliness · health crisis · seeking aid · winter test · hidden hope', ja: '物質的困難・孤独・健康危機・援助を求める・冬の試練・隠れた希望' },
  69: { zh: '慷慨、施舍、公正、物质援助、互惠、权力平衡', en: 'Generosity · Charity · Justice · Material aid · Reciprocity · Balance of power', ja: '寛容・施し・正義・物質的援助・互恵・権力のバランス' },
  70: { zh: '耐心、评估、等待、成长、长期规划、时间', en: 'Patience · Evaluation · Waiting · Growth · Long-term planning · Time', ja: '忍耐・評価・待つ・成長・長期計画・時間' },
  71: { zh: '专注、踏实、磨练、技艺、重复、耐心', en: 'diligence · craftsmanship · mastery · focus · practice · refinement', ja: '勤勉・熟練・集中・努力・向上・忍耐' },
  72: { zh: '物质丰饶、独立自主、自我价值、优雅自律、享受成果、稳定富足', en: 'Material abundance · Independence · Self-worth · Elegant discipline · Enjoying results · Stable prosperity', ja: '物質的豊かさ・自立・自己価値・優雅な規律・成果を楽しむ・安定した繁栄' },
  73: { zh: '家族财富、稳定根基、传承与累积、物质丰盛、家庭责任、长期回报', en: 'legacy · stability · family · wealth · tradition · security', ja: '富・安定・家族・遺産・伝統・完成' },
  74: { zh: '务实、学习、专注、机会、基础、谨慎', en: 'practical · learning · focus · opportunity · foundation · caution', ja: '実用・学習・集中・機会・基礎・慎重' },
  75: { zh: '务实、耐心、可靠、稳定、责任、坚持', en: 'practicality · patience · reliability · stability · responsibility · persistence', ja: '実用性・忍耐・信頼性・安定・責任・持続' },
  76: { zh: '丰饶、务实、滋养、大地母亲、稳定、慷慨', en: 'abundance · practicality · nurturing · Earth Mother · stability · generosity', ja: '豊穣・実用性・養育・地母神・安定・寛大さ' },
  77: { zh: '务实、稳定、财富、丰饶、掌控、责任', en: 'pragmatic · stable · wealth · abundance · mastery · responsibility', ja: '現実的・安定・富・豊穣・支配・責任' },
};
