-- mustar.vip 客户账户体系
-- 在 Supabase SQL Editor 执行一次；不会覆盖 profiles / user_roles / user_archives 等既有表。
--
-- 本次启用（代码已接入）：
--   user_spreads      自定义牌阵（塔罗 / 雷诺曼）
--   reading_sessions  解读历史（含追问对话）
-- 预留（表已建好，代码未接入，等规则定下来再填逻辑）：
--   credit_ledger     积分流水（账本模式：余额由流水汇总，不存单一余额字段）
--   orders            充值订单
--   invitations       邀请关系
--
-- 设计要点：积分采用「账本」而非「余额字段」，任何一笔变动都留痕，
-- 用户能看到明细，客服也能追溯；余额由 credit_ledger 汇总得出。

-- ============================================================
-- 1. 自定义牌阵
-- ============================================================
create table if not exists public.user_spreads (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  deck text not null default 'tarot' check (deck in ('tarot', 'lenormand')),
  name text not null,
  -- 格位数组：[{ row, col, cols, name }]（与 CustomSpreadBuilder 的 CustomCell 一致）
  cells jsonb not null default '[]'::jsonb,
  -- 牌阵说明：专业师会写这个牌阵怎么读、有什么讲究
  description text not null default '',
  -- 用途标签（感情 / 事业 / 灵性 …），供检索
  tags text[] not null default '{}',
  -- 预留：是否公开分享。当前策略未开放，仅本人可见。
  is_public boolean not null default false,
  -- 使用次数：专业师关心哪个牌阵最常用
  use_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- 同一用户在同一牌组下不允许同名牌阵（与布阵器「同名覆盖」行为一致）
  unique (user_id, deck, name)
);

create index if not exists user_spreads_user_idx on public.user_spreads (user_id, deck, updated_at desc);

-- ============================================================
-- 2. 解读历史
-- ============================================================
create table if not exists public.reading_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  deck text not null default 'tarot' check (deck in ('tarot', 'lenormand')),
  spread_key text,
  spread_name text not null default '',
  question text not null default '',
  background text not null default '',
  positions text[] not null default '{}',
  -- 自定义牌阵格位（quick / custom 时才有）
  custom_layout jsonb,
  -- 抽到的牌：[{ id, name, reversed }]
  cards jsonb not null default '[]'::jsonb,
  -- AI 解读全文
  interpretation text not null default '',
  -- 追问对话：[{ role, content, cards? }]
  chat jsonb not null default '[]'::jsonb,
  -- 追问时新抽的牌
  extra_cards jsonb not null default '[]'::jsonb,
  lang text not null default 'zh',
  -- 关联的出生档案（若有）
  archive_id uuid,
  -- 客户维度：专业师给谁解的（"张三""李女士"），支持按客户筛选历史
  client_label text not null default '',
  -- 准 / 不准
  rating smallint check (rating in (-1, 1)),
  -- 摘要：将来清理全文后保留这一行 + 牌面
  summary text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists reading_sessions_user_idx on public.reading_sessions (user_id, created_at desc);
create index if not exists reading_sessions_client_idx on public.reading_sessions (user_id, client_label);

-- ============================================================
-- 3. 积分流水（预留：表已建好，代码未接入）
-- ============================================================
create table if not exists public.credit_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  -- 正数为增加，负数为扣减
  delta integer not null,
  -- 变动原因：signup / recharge / reading / invite / refund / expire / admin
  reason text not null,
  -- 关联对象（如某次解读、某笔订单）
  ref_type text,
  ref_id text,
  -- 变动后余额（写入时快照，便于对账；真实余额仍以汇总为准）
  balance_after integer,
  note text not null default '',
  -- 过期时间：若采用「积分有效期」策略，此处记录该笔积分的到期日
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists credit_ledger_user_idx on public.credit_ledger (user_id, created_at desc);

-- ============================================================
-- 4. 充值订单（预留：表已建好，代码未接入）
-- ============================================================
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  -- 金额以「分」为单位存整数，避免浮点误差
  amount_cents integer not null,
  currency text not null default 'CNY',
  -- 本单兑换的积分数
  credits integer not null default 0,
  -- 支付渠道：wechat / alipay / stripe …
  provider text,
  provider_order_id text,
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'failed', 'refunded', 'cancelled')),
  paid_at timestamptz,
  refunded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists orders_user_idx on public.orders (user_id, created_at desc);
create unique index if not exists orders_provider_order_idx
  on public.orders (provider, provider_order_id)
  where provider_order_id is not null;

-- ============================================================
-- 5. 邀请关系（预留：表已建好，代码未接入）
-- ============================================================
create table if not exists public.invitations (
  id uuid primary key default gen_random_uuid(),
  inviter_id uuid not null references auth.users(id) on delete cascade,
  invitee_id uuid references auth.users(id) on delete set null,
  code text not null,
  -- pending=已注册未达标 / qualified=已达标可发放 / rejected=判定为刷号
  status text not null default 'pending'
    check (status in ('pending', 'qualified', 'rejected')),
  -- 奖励是否已发放（延迟发放：被邀请人首次真实消费后才置 true）
  reward_granted boolean not null default false,
  -- 防刷辅助：注册时记录设备指纹，同一指纹多号可判定为异常
  device_fingerprint text,
  created_at timestamptz not null default now(),
  qualified_at timestamptz,
  unique (inviter_id, invitee_id)
);

create index if not exists invitations_inviter_idx on public.invitations (inviter_id, created_at desc);
create unique index if not exists invitations_code_idx on public.invitations (code);

-- ============================================================
-- RLS：所有表一律「仅本人可读写」，权限边界在数据库而非前端
-- ============================================================
alter table public.user_spreads enable row level security;
alter table public.reading_sessions enable row level security;
alter table public.credit_ledger enable row level security;
alter table public.orders enable row level security;
alter table public.invitations enable row level security;

drop policy if exists user_spreads_own on public.user_spreads;
create policy user_spreads_own on public.user_spreads
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists reading_sessions_own on public.reading_sessions;
create policy reading_sessions_own on public.reading_sessions
for all to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- 积分流水：用户只能读自己的，写入一律走服务端（service role），前端不可写
drop policy if exists credit_ledger_self_read on public.credit_ledger;
create policy credit_ledger_self_read on public.credit_ledger
for select to authenticated
using (auth.uid() = user_id);

-- 订单：用户只能读自己的，写入由支付回调以服务端身份完成
drop policy if exists orders_self_read on public.orders;
create policy orders_self_read on public.orders
for select to authenticated
using (auth.uid() = user_id);

-- 邀请：邀请人可读自己发出的邀请
drop policy if exists invitations_self_read on public.invitations;
create policy invitations_self_read on public.invitations
for select to authenticated
using (auth.uid() = inviter_id or auth.uid() = invitee_id);

-- ============================================================
-- 说明
-- ============================================================
-- · is_public / 分享功能：字段已预留，但当前 RLS 只允许本人访问。
--   将来开放分享时，需追加一条「公开牌阵可被任何登录用户读取」的 select 策略。
-- · 解读全文体积较大，保留策略（如最近 20 条存全文、更早只留 summary + cards）
--   待定价与容量规划确定后再实现，当前不做清理。
-- · 不要在前端使用 service role key；积分与订单的写入必须经服务端校验。
