-- mustar.vip 管理后台 MVP
-- 在 Supabase SQL Editor 执行一次；不会覆盖现有 user_archives/card_meanings/learn_articles。

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'admin', 'operator', 'support', 'editor')),
  disabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do update set email = excluded.email, updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into public.profiles (id, email)
select id, email from auth.users
on conflict (id) do update set email = excluded.email, updated_at = now();

alter table public.profiles enable row level security;
alter table public.user_roles enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists profiles_self_read on public.profiles;
create policy profiles_self_read on public.profiles
for select to authenticated using (auth.uid() = id);

drop policy if exists roles_self_read on public.user_roles;
create policy roles_self_read on public.user_roles
for select to authenticated using (auth.uid() = user_id);

drop policy if exists audit_self_read on public.audit_logs;
create policy audit_self_read on public.audit_logs
for select to authenticated using (auth.uid() = actor_id);

-- 第一个 owner 必须替换成实际管理员邮箱后再执行；不要把 service role key 写入代码或 SQL。
-- insert into public.user_roles (user_id, role)
-- select id, 'owner' from auth.users where email = '你的管理员邮箱'
-- on conflict (user_id) do update set role = 'owner', disabled = false, updated_at = now();
